package com.example.apphistoriamexico;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class AdmiSQLiteOpenHelper extends SQLiteOpenHelper {


    public AdmiSQLiteOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase BasesDeDatos) {

    // Tabla tipo Actividad
        BasesDeDatos.execSQL("Create table t_tipo_actividad(id int primary Key, nom_actividad text, icono text, activo int)");
        BasesDeDatos.execSQL("INSERT INTO t_tipo_actividad(id, nom_actividad, icono, activo ) VALUES (1, 'Reto Saber', '', 1), (2, 'Cuestionario', '', 1)");

    // Tabla Estudios
        BasesDeDatos.execSQL("CREATE TABLE t_estudios(id INTEGER PRIMARY KEY AUTOINCREMENT, fecha date, co_actividad int)");
        BasesDeDatos.execSQL("CREATE TABLE t_estadisticas(id INTEGER PRIMARY KEY AUTOINCREMENT, co_estudios int, co_pregunta int, co_nivel int, co_categoria int, validacion int)");


    // Tabla de categoria
        BasesDeDatos.execSQL("CREATE TABLE t_categoria(id int primary Key, nom_categoria text, desp_categoria text, activo int)");
        BasesDeDatos.execSQL("INSERT INTO t_categoria(id, nom_categoria, desp_categoria, activo) VALUES (1, 'Curiosidades ', 'curiosidad', 1), (2, 'Comida', 'comida', 1),(3, 'Cine', 'cine', 1),(4, 'Musica / Arte', 'arte', 1),(5, 'Deporte', 'deporte', 1),(6, 'Prehispánica', 'prehispanica', 1),(7, 'Nueva España', 'deporte', 1),(8, 'Independencia ', 'independencia', 1),(9, 'Revolución', 'revolucion', 1),(10, 'Historia Comtemponranea', 'historiamoderna', 1),(11, 'Geografía', 'geografia', 1),(12, 'Legislación Política ', 'legislacion', 1)");

     // Tabla Niveles de aprendizaje

        BasesDeDatos.execSQL("CREATE TABLE t_niveles(id int primary Key, nom_nivel text, icono text, activo int)");
        BasesDeDatos.execSQL("INSERT INTO t_niveles(id,  nom_nivel, icono, activo) VALUES (1, 'Básico', 'basico', 1), (2, 'Medio', 'medio', 1), (3, 'Avanzado', 'avanzado', 1), (4, 'Experto', 'experto', 1), (5, 'Leyenda', 'leyenda', 1)");


    // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL BASICO -
        BasesDeDatos.execSQL("CREATE TABLE t_preguntas(id int primary Key, co_categoria int, co_nivel int, co_respuesta int, pregunta text, respuesta text, enlace_resp text, imagen_pre text, imagen_resp text, activo int)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (1, 1, 1, 1, '¿Cuáles son los Premios Nobel por mexicanos?', 'Premio Nobel de la Paz en 1982 Alfonso García Robles', 'https://es.wikipedia.org/wiki/Categor%C3%ADa:Premios_Nobel_de_M%C3%A9xico', '0', '0', 1), (2, 1, 1, 2, '¿ Cuál es el Árbol Nacional? ', 'Ahuehuete o árbol de tule', 'https://www.gob.mx/conafor/articulos/el-arbol-nacional?idiom=es', '0', '0', 1), (3, 1, 1, 3, '¿ Cuál es el Animal Nacional ?', 'Aguila Real', 'https://www.mexicodesconocido.com.mx/aguila-real-mexicana.html', '0', '0', 1), (4, 1, 1, 4, '¿ Cuál es la flor Nacional ? ', 'Dalia', 'https://www.gob.mx/semarnat/articulos/dalia-flor-representativa-de-mexico?idiom=es', '0', '', 1), (5, 1, 1, 5, '¿ El tema dominante del himno nacional mexicano ? ', 'Una exhortación a la guerra defensiva ', 'https://www.gob.mx/semarnat/articulos/dalia-flor-representativa-de-mexico?idiom=es', '0', '', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (6, 1, 1, 6, '¿ Cuando fue declarado oficial el himno nacional ?', 'En 1943 durante la presidencia de Manuel Ávila Camacho', 'https://www.gob.mx/inafed/articulos/conmemoramos-que-hace-76-anos-se-emitio-el-decreto-por-el-que-se-establece-la-version-oficial-de-nuestro-himno-nacional', '0', '0', 1), (7, 1, 1, 7, '¿ Cual de los símbolos patrios fue reconocido oficialmente en 1943 ?', 'El Himno Nacional', 'https://www.gob.mx/inafed/articulos/conmemoramos-que-hace-76-anos-se-emitio-el-decreto-por-el-que-se-establece-la-version-oficial-de-nuestro-himno-nacional', '0', '0', 1), (8, 1, 1, 8, '¿ El águila y la serpiente que aparecen en el escudo nacional mexicano, incluido en la franja blanca de la bandera evoca a una ?', 'Evocan una leyenda prehispánica', 'https://es.wikipedia.org/wiki/Escudo_Nacional_de_M%C3%A9xico', '0', '0', 1), (9, 1, 1, 9, '¿ Perro Originario de México o Nombre de raza de perro prehispánico de poco pelo ?', 'Xoloitzcuintle', 'https://es.wikipedia.org/wiki/Xoloitzcuintle', '0', '', 1), (10, 1, 1, 10, '¿ A qué se le llama Fonda ?', 'Es un pequeño restaurante económico', '', '0', '', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (11, 1, 1,11, '¿ En México las estaciones de taxis se conocen como ?', 'Sitios', '0', '0', '0', 1), (12, 1, 1, 12, '¿ En México una tlapalería es ?', 'Una tienda de pinturas y solventes ', '0', '0', '0', 1), (13, 1, 1, 13, '¿ El vocablo chaparro significa ?', 'Bajo de estatura', '0', '0', '0', 1) , (14, 1, 1, 14, '¿ En el habla popular de México el término marchante que significado tiene ?', 'Se aplica de igual manera al comprador y al vendedor', '0', '0', '0', 1), (15, 1, 1, 15, '¿ La palabra jarocho alude a lo que es propio de ?', 'Veracruz', 'https://www.destinoveracruz.com/2012/09/origen-palabra-jarocho.html', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (16, 1, 1,16, '¿ Tradiciones de México fiestas patrias ?', 'Grito de Independencia 16 de septiembre', 'https://www.mexicodesconocido.com.mx/las-fiestas-patrias-en-mexico.html', '0', '0', 1), (17, 1, 1, 17, '¿ Que significa papalote ?', 'Mariposa o Cometa ', '0', '0', '0', 1), (18, 1, 1, 18, '¿ Cual es el lema de la Universidad Autónoma  Metropolitana (UAM) ?', 'Casa abierta al tiempo', 'http://www.uam.mx/identidad/emblemaylema/index.html', '0', '0', 1) , (19, 1, 1, 19, '¿ Sistema de Acueducto de CDMX y EDOmex ?', 'Sistema Cutzamala', '0', '0', '0', 1)");

    // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL MEDIO -

        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (20, 1, 2, 20, '¿ Cuantos museos hay en México ?', 'El territorio nacional existen mas de 300 mil museos', 'https://www.eluniversal.com.mx/cultura/en-mexico-existen-mil-300-museos', '0', '0', 1), (21, 1, 2, 21, '¿ Cuántos museos hay en la CDMX ?', '155 según la secretaria de la cultura', '0', '0', '0', 1) , (22, 1, 2, 22, 'La Plaza de la Constitución Zócalo recibe su nombre en honor a ¿ Cuál constitución ?', 'La Constitución de Cádiz de 1812', '0', '0', '0', 1) , (23, 1, 2, 23, '¿ Las posadas son fiestas privadas o vecinales que se realizan: ?', 'Los días previos a la Navidad ', '0', '0', '0', 1) , (24, 1, 2, 24, '¿ Es costumbre cantar Las golondrinas para: ?', 'Despedir a alguien ', '0', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (25, 1, 2, 25, '¿ En los cumpleaños se suele cantar en homenaje al festejado?', 'Las mañanitas', '0', '0', '0', 1)  , (26, 1, 2, 26, '¿ Principales puertos turísticos ?', 'Cozumel, Acapulco, Mazatlán', '0', '0', '0', 1)  , (27, 1, 2, 27, ' ¿ Los Pinos es ? ', 'La residencia oficial del presidente de la República, Hasta el 2018 ', '0', '0', '0', 1)  , (28, 1, 2, 28, '¿ Versos festivos que se escriben en noviembre con motivo del Día de muertos ?', 'Calaveras o Calaveritas', '0', '0', '0', 1)  , (29, 1, 2, 29, '¿ Quién ganó el Premio Nobel de Química por haber identificado las propiedades químicas que debilitan la capa de ozono?', 'Mario José Molina Henríquez', '0', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (30, 1, 2, 30, '¿ ¿Quién ganó el Premio Pritzker? (Premio Nobel de la Arquitectura) ?', 'Luis Barragán en 1980  ', 'https://obrasweb.mx/pritzkers/2013/12/09/luis-barragan', '0', '0', 1)  , (31, 1, 2, 31, '¿ Quién fue el primer astronauta mexicano  ?', ' Rodolfo Neri Vela ', 'http://rodolfonerivela.com/', '0', '0', 1)  , (32, 1, 2, 32, ' ¿ Cuantos Patrimonios de la Humanidad de la UNESCO tiene México ? ', ' Hasta el 2018, México cuenta con 33 sitios ', 'https://www.animalpolitico.com/2017/02/los-33-patrimonios-la-humanidad-hacen-mexico-pais-especial/', '0', '0', 1)  , (33, 1, 2, 33, '¿ Cuantos Patrimonios de la Humanidad Culturales de la UNESCO tiene México  ?', ' 35 ', 'https://es.wikipedia.org/wiki/Anexo:Patrimonio_de_la_Humanidad_en_M%C3%A9xico.', '0', '0', 1)  , (34, 1, 2, 34, '¿ Patrimonio de la humanidad  ?', ' - La charrería, arte ecuestre y vaquero tradicional de México.   - El mariachi, música de cuerdas, canto y trompeta.   ', '0', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (35, 1, 2, 35, '¿ Lugar reconocido como Patrimonio de la Humanidad según la UNESCO ?', ' Chichen Itzá  ', 'https://es.wikipedia.org/wiki/Anexo:Patrimonio_de_la_Humanidad_en_M%C3%A9xico.', '0', '0', 1)  , (36, 1, 2, 36, '¿ Celebración reconocida como Patrimonio Cultural Inmaterial de la Humanidad de la UNESCO ?', 'Día de muertos   ', 'https://www.gob.mx/imjuve/articulos/dia-de-muertos-patrimonio-cultural-inmaterial-de-la-humanidad ', '0', '0', 1)  , (37, 1, 2, 37, ' Qué música forma parte del Patrimonio Cultural de la Humanidad ', ' El mariachi ', 'https://inah.gob.mx/boletines/1456-mariachi-patrimonio-de-la-humanidad-unesco', '0', '0', 1)  , (38, 1, 2, 38, '¿  Patrimonio cultural de la humanidad para las ciencias y la cultura ?', ' Voladores de Papantla  ', 'http://wradio.com.mx/radio/2009/09/30/nacional/1254341520_887939.html', '0', '0', 1)  , (39, 1, 2, 39, '¿ Cuál de los siguientes sitios NO es Patrimonio UNESCO de México  ?', ' Tikal ', 'https://es.wikipedia.org/wiki/Tikal', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (40, 1, 2, 40, '¿ Lugar decretado como patrimonio mundial por la UNESCO en 1992 ?', ' Ciudad Prehispánica de El Tajín ', 'https://www.inah.gob.mx/boletines/2395-el-tajin-patrimonio-mundial', '0', '0', 1)  , (41, 1, 2, 41, '¿ Qué son los Voladores de Papantla ?', ' Danza indígena de Veracruz. Manifestación religiosa de invocación de la lluvia y el maíz, es decir, relacionada a la fertilidad. Sus orígenes se remontan al Período Preclásico Medio mesoamericano. ', 'https://www.mexicodesconocido.com.mx/los-voladores-de-papantla.html', '0', '0', 1)  , (42, 1, 2, 42, '¿ El Zocalo de la Ciudad de México es conocido como ?   ', ' La Plaza de la Constitución. ', 'https://es.wikipedia.org/wiki/Plaza_de_la_Constituci%C3%B3n_(Ciudad_de_M%C3%A9xico)', '0', '0', 1)  , (43, 1, 2, 43, '¿ Que construcciones significativa se encuentran en el Zócalo de la CDMX ?', 'La Plaza de la Constitución  ', 'https://es.wikipedia.org/wiki/Plaza_de_la_Constituci%C3%B3n_(Ciudad_de_M%C3%A9xico)', '0', '0', 1)  , (44, 1, 2, 44, '¿ Fecha que se conmemora el día de las madres en México ?', ' 10 de mayo ', 'https://es.wikipedia.org/wiki/D%C3%ADa_de_la_Madre#En_M%C3%A9xico', '0', '0', 1)");


    // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL AVANZADO -

       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (45, 1, 3, 45, '¿  Cuál es la ciudad de la Puerta Oro del Bajío ?', ' Celaya ', 'https://www.mexicotravelclub.com/celaya-en-celaya-guanajuato', '0', '0', 1) , (46, 1, 3, 46, '¿  Cuál Puerto fue defendido 4 veces por sus habitantes héroes? ', ' Puerto de Verazruz', 'http://internacionales.pri.org.mx/sabiasque/Sabias.aspx?y=4792', '0', '0', 1) , (47, 1, 3, 47, ' ¿Cuál es el estado con mayor producción de calzado?  ', ' Guanajuato ', 'https://www.gob.mx/se/articulos/la-industria-del-calzado-en-mexico', '0', '0', 1) , (48, 1, 3, 48, '¿ Quién inventó el televisor a color  ?', ' Guillermo González Camarena en 1940 ', 'https://es.wikipedia.org/wiki/Guillermo_Gonz%C3%A1lez_Camarena', '0', '0', 1) , (49, 1, 3, 49, '¿  Quién es el ingeniero Camarena ?', ' Científico, investigador e ingeniero mexicano. ', 'https://es.wikipedia.org/wiki/Guillermo_Gonz%C3%A1lez_Camarena', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (50, 1, 3, 50, '¿  Quién es Luis Ernesto Miramontes Cárdenas  ?', 'Químico', 'https://es.wikipedia.org/wiki/Luis_Ernesto_Miramontes', '0', '0', 1), (51, 1, 3, 51, '¿ Quién inventó el primer anticonceptivo oral ?', ' Luis Ernesto Miramontes Cárdenas ', 'https://es.wikipedia.org/wiki/Luis_Ernesto_Miramontes', '0', '0', 1) , (52, 1, 3, 52, ' ¿Cuándo se fundó el metro en la CDMX ? ', ' El 4 de septiembre de 1969  ', 'https://es.wikipedia.org/wiki/L%C3%ADnea_1_del_Metro_de_la_Ciudad_de_M%C3%A9xico', '0', '0', 1) , (53, 1, 3, 53, '¿ Que presidente inauguró el metro de CDMX  ?', 'Gustavo Diaz Ordaz  ', 'https://es.wikipedia.org/wiki/Metro_de_la_Ciudad_de_M%C3%A9xico', '0', '0', 1) , (54, 1, 3, 54, '¿ Que significa el refrán a darle que es mole de olla  ?', ' invitación a hacer alguna cosa con buen ánimo y sin demora ', 'https://www.significados.com/a-darle-que-es-mole-de-olla', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (55, 1, 3, 55, '¿  Cuando se inauguró el ángel de la independencia ?', '16 de septiembre de 1910', 'https://es.wikipedia.org/wiki/Monumento_a_la_Independencia', '0', '0', 1) , (56, 1, 3, 56, '¿  Cuando se cayó el ángel de la independencia ?', ' 28 de julio de 1957', 'https://www.eluniversal.com.mx/articulo/cultura/patrimonio/2017/07/28/el-dia-que-se-cayo-el-angel-de-la-independencia#imagen-1', '0', '0', 1) , (57, 1, 3, 57, ' ¿ Cuándo fue el terremoto que tumbó una iglesia Puebla ? ', '19 de septiembre 2017', 'https://www.eluniversal.com.mx/cultura/patrimonio/sismo-deja-danos-en-catedral-metropolitana-y-en-iglesias-de-la-ciudad#imagen-1', '0', '0', 1) , (58, 1, 3, 58, '¿ En qué año se cambió el nombre de Distrito Federal DF a Ciudad de México CDMX  ?', '29 Enero 2016  ', 'https://expansion.mx/economia/2016/01/29/pena-nieto-promulga-la-reforma-politica-de-la-cdmx', '0', '0', 1) , (59, 1, 3, 59, '¿  De dónde es la guelaguetza ?', ' De OAXACA ', 'https://es.wikipedia.org/wiki/Guelaguetza', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (60, 1, 3, 60, '¿  Que es la guelaguetza ?', 'Guelaguetza es una palabra de origen zapoteco y se refiere a la cortesía, a la delicadeza y atención con que se debe tratar a los demás  ', 'https://es.wikipedia.org/wiki/Guelaguetza', '0', '0', 1) , (61, 1, 3, 61, '¿ Cuantas zonas arqueológicas tiene el INAH ?', '189  ', 'https://www.inah.gob.mx/zonas/5410-red-de-zonas-arqueologicas-del-inah', '0', '0', 1) , (62, 1, 3, 62, '¿ En que año se fundó la UNAM ?  ', ' 22 Septiembre 1910  ', 'http://de10.com.mx/top-10/2018/09/22/10-datos-para-conocer-mas-sobre-el-origen-de-la-unam', '0', '0', 1) , (63, 1, 3, 63, '¿ Como se llama dónde van a parar los fiesteros ?', ' El Torito ', 'http://www.eluniversal.com.mx/entrada-de-opinion/colaboracion/mochilazo-en-el-tiempo/nacion/sociedad/2017/07/1/por-que-se-llama', '0', '0', 1) , (64, 1, 3, 64, '¿ Primer secretario de educación de México ?', ' José Vasconcelos ', 'http://difusionfractal.upnvirtual.edu.mx/index.php/blog/326-quien-fue-jose-vasconcelos', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (65, 1, 3, 65, '¿  Que lugar de la economía mundial ocupa Mexico  ?', ' 15 ', 'https://www.gob.mx/cms/uploads/attachment/file/43882/MEX_Ficha_resumen.pdf', '0', '0', 1), (66, 1, 3, 66, '¿ A que se conoce como la bella airosa  ?', ' A La Ciudad de Pachuca estado de Hidalgo ', 'http://www.guiahidalgo.com.mx/blog-de-hidalgo/1-la-leyenda-de-la-bella-airosa.html', '0', '0', 1), (67, 1, 3, 67, ' ¿ Quiénes fueron las mexicanas ganadoras del Miss Universo ? ', ' 1era Maria Guadalupe jones - 1991 y la 2da Ximena Navarrete (2010)  ', '0', '0', '0', 1) , (68, 1, 3, 68, '¿ Quien dijo la patria es primero  ?', ' Vicente Guerrero ', 'http://fundacioncarlosslim.org/la-patria-primero', '0', '0', 1) , (69, 1, 3, 69, '¿ Que significa  Axayácatl ?', 'El de la máscara de agua  ', 'https://arqueologiamexicana.mx/mexico-antiguo/axayacatl-el-de-la-mascara-de-agua-1469-1481', '0', '0', 1)");

    // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL EXPERTO  -
/*
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (70, 1, 4, 70, '¿ Cómo se llama el famoso callejón de Guanajuato ?', ' El callejón del beso ', 'https://www.youtube.com/watch?time_continue=141&v=HrUw5aB9p00', '0', '0', 1), (71, 1, 4, 71, '¿ El palacio de Axcayatl también conocido como  ?', ' Las casas viejas de Moctezuma ', 'http://www.wikimexico.com/articulo/las-casas-viejas-de-moctezuma', '0', '0', 1), (72, 1, 4, 72, ' La Ciudad de México es conocida cómo ', 'la Ciudad de los Palacios  ', 'http://www.voyvengo.com.mx/revista/item/la-ciudad-de-los-palacios', '0', '0', 1), (73, 1, 4, 73, '¿ Cuales animales mexicanos están en peligro de extinción  ?', ' Ajolote, Guacamaya roja, Lobo gris mexicano, Jaguar, Tortuga caguama, Perrito llanero mexicano y Vaquita marina ', 'https://novedadesaca.mx/7-especies-fauna-en-peligro-extincion-en-mexico', '0', '0', 1), (74, 1, 4, 74, '¿ La estructura donde se construiría el palacio legislativo federal ?', 'Monumento a la Revolución (1933)  ', 'https://expansion.mx/obras/de-palacio-legislativo-a-monumento', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (75, 1, 4, 75, '¿ Cuál fue el palacio construido para ser legislativo pero terminó siendo algo más  ?', 'Monumento de la Revolución', 'https://expansion.mx/obras/de-palacio-legislativo-a-monumento', '0', '0', 1)  , (76, 1, 4, 76, '¿ En dónde se encuentran las pirámides del Sol y la Luna  ?', ' Teotihuacan ', 'https://inah.gob.mx/zonas/23-zona-arqueologica-de-teotihuacan', '0', '0', 1)  , (77, 1, 4, 77, ' ¿ Cuál es el teatro de mayor prestigio en la ciudad de México ?', ' Palacio de Bellas Artes ', 'https://www.inba.gob.mx/sitios/recorridos-virtuales/palacio-de-bellas-artes', '0', '0', 1)  , (78, 1, 4, 78, '¿ Cuál es la flor amarilla que se usa durante día de muertos  ?', ' Cempasúchil ', 'http://cdmxtravel.com/es/experiencias/la-flor-de-cempasuchil-y-su-importancia-en-nuestra-cultura.html', '0', '0', 1)  , (79, 1, 4, 79, '¿Con qué otro nombre se conoce a la Diana La Cazadora ?', ' Flechadora de las Estrellas del Norte ', 'http://www.ciudadmexico.com.mx/atractivos/diana.htm', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (80, 1, 4, 80, '¿ Qué significa CONALEP ?', ' Colegio Nacional de Educación Profesional Técnica ', ' https://www.gob.mx/conalep ', '0', '0', 1)  , (81, 1, 4, 81, '¿ Localidad de CDMX en donde en Semana Santa celebran la Pasión de Cristo  ?', ' Iztapalapa ', 'https://www.mexicodesconocido.com.mx/la-pasion-de-cristo-en-iztapalapa-distrito-federal.html', '0', '0', 1)  , (82, 1, 4, 82, ' En qué año comenzaron las obras del ferrocarril ', ' 1842 ', 'https://www.mexicodesconocido.com.mx/ferrocarril-ruta-vital.html', '0', '0', 1)  , (83, 1, 4, 83, '¿ En qué año se inauguraron las obras del ferrocarril ?', ' 1850 ', 'http://www.estaciontorreon.galeon.com/productos627821.html', '0', '0', 1)  , (84, 1, 4, 84, '¿Cómo se llama la tribu que es originaria de Michoacán?', ' Purepechas ', 'https://www.lifeder.com/grupos-etnicos-michoacan', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (85, 1, 4, 85, '¿ Cuál es la cultura indígena que persiste en el norte del país ?', 'Tarahumara', 'https://www.gob.mx/inpi/articulos/etnografia-del-pueblo-tarahumara-raramuri', '0', '0', 1)  , (86, 1, 4, 86, '¿ Cuántas lenguas indígenas existen ?', '68 Mas el Español ', 'https://www.gob.mx/cultura/articulos/lenguas-indigenas?idiom=es', '0', '0', 1)  , (87, 1, 4, 87, ' ¿ Cuál fue la primera institución educativa en 1811 destinada a las ciencias y artes ?  ', ' Colegio de Minería ', '0', '0', '0', 1)  , (88, 1, 4, 88, '¿ Versos festivos que se escriben en noviembre con motivo del Día de muertos ?', ' Calaveras literarias ', 'https://www.gob.mx/cultura/articulos/lenguas-indigenas?idiom=es', '0', '0', 1)  , (89, 1, 4, 89, '¿ Cuáles productos exporta Mexico ?', ' Tomate, cebolla, chiles y pimientos, limón, aguacate, pepino, sandía,  papaya, azúcar de caña, frutos rojos, cerveza,tequila, aceite crudo de petróleo, autopartes y productos de cobre ', 'https://www.animalpolitico.com/2017/01/aguacate-tequila-productos-exporta', '0', '0', 1)");
        BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (90, 1, 4, 90, '¿ Qué significa cada símbolo patrio ?', ' Bandera: el Verde simboliza la esperanza del pueblo en el destino de su raza, el Blanco representa la pureza de los ideales del pueblo y el Rojo simboliza la sangre que derramaron los héroes por la patria.', '0', '0', '0', 1)  , (91, 1, 4, 91, '¿ Qué significa el nombre de México ?', ' Ombligo de la luna ', 'http://etimologias.dechile.net/?Me.xico', '0', '0', 1)  , (92, 1, 4, 92, ' Cuál es el significado de la palabra Cuauhtémoc ', ' El águila se posó o el águila que descendió ', 'https://es.wikipedia.org/wiki/Cuauht%C3%A9moc', '0', '0', 1)  , (93, 1, 4, 93, '¿ Quién nacionalizó la banca  ?', ' José López Portillo ', 'https://es.wikipedia.org/wiki/Nacionalizaci%C3%B3n_de_la_banca_en_M%C3%A9xico', '0', '0', 1)  , (94, 1, 4, 94, '¿ A que hace referencia la Estela de la Luz  ?', ' Monumento en conmemoración del Bicentenario de la Independencia Mexicana y del Centenario de la Revolución Mexicana. ', 'https://www.eluniversal.com.mx/cultura/cinco-datos-que-debes-conocer-de-la-estela-de-luz', '0', '0', 1)");
*/
    // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL lEYENDA   -

       /*
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (95, 1, 5, 45, '¿  ?', '  ', '0', '0', '0', 1)  , (96, 1, 5, 46, '¿  ?', '  ', '0', '0', '0', 1)  , (97, 1, 5, 47, '  ', '  ', '0', '0', '0', 1)  , (98, 1, 5, 48, '¿   ?', '  ', '0', '0', '0', 1) , (99, 1, 5, 49, '¿   ?', '  ', '0', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (100, 1, 5, 50, '¿  ?', '  ', '0', '0', '0', 1)  ,(101, 1, 5, 51, '¿  ?', '  ', '0', '0', '0', 1) , (102, 1, 5, 52, '  ', '  ', '0', '0', '0', 1) , (103, 1, 5, 53, '¿   ?', '  ', '0', '0', '0', 1) ,(104, 1, 5, 54, '¿   ?', '  ', '0', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (105, 1, 5, 55, '¿  ?', '  ', '0', '0', '0', 1)  ,(106, 1, 5, 56, '¿  ?', '  ', '0', '0', '0', 1) , (107, 1, 5, 57, '  ', '  ', '0', '0', '0', 1) , (108, 1, 5, 58, '¿   ?', '  ', '0', '0', '0', 1) ,(109, 1, 5, 59, '¿   ?', '  ', '0', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (110, 1, 5, 60, '¿  ?', '  ', '0', '0', '0', 1)  ,(111, 1, 5, 61, '¿  ?', '  ', '0', '0', '0', 1) , (112, 1, 5, 62, '  ', '  ', '0', '0', '0', 1) , (113, 1, 5, 63, '¿   ?', '  ', '0', '0', '0', 1) ,(114, 1, 5, 64, '¿   ?', '  ', '0', '0', '0', 1)");
       BasesDeDatos.execSQL("INSERT INTO t_preguntas (id, co_categoria, co_nivel, co_respuesta, pregunta, respuesta, enlace_resp, imagen_pre, imagen_resp, activo) VALUES (115, 1, 5, 65, '¿  ?', '  ', '0', '0', '0', 1)  ,(116, 1, 5, 66, '¿  ?', '  ', '0', '0', '0', 1) , (117, 1, 5, 67, '  ', '  ', '0', '0', '0', 1) , (118, 1, 5, 68, '¿   ?', '  ', '0', '0', '0', 1) ,(119, 1, 5, 69, '¿   ?', '  ', '0', '0', '0', 1)");
        */



        // tabla de complemento -TANDA CAT. COMIDA - NIVEL BASICO -

        BasesDeDatos.execSQL("CREATE TABLE t_complemento(id int primary Key, co_pregunta int, complemento text, imagen text, activo int)");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (1, 1,  'Premio Nobel de la Paz en 1982 Manuel Tolsa', '0', 1), (2, 1, 'Premio Nobel de la Paz en 1982 Maria Felix', '0', 1), (3, 1, 'Premio Nobel de la Paz en 1982 Octavio Paz', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (4, 2,  'Ar bol Nacional', '0', 1), (5, 2, 'Sabino', '0', 1), (6, 2, 'Cedro Blanco', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (7, 3,  'Xoloitzcuintle', '0', 1), (8, 3, 'Águila calva', '0', 1), (9, 3, 'Los colibríes', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (10, 4, 'Cempasúchil', '0', 1), (11, 4, 'Tulipanes', '0', 1), (12, 4, 'Orquidea', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (13, 5, 'Paz Universal', '0', 1), (14, 5, 'Venganza a nuestros pueblos', '0', 1), (15, 5, 'Siempre venceremos', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (16, 6,  'En 1821 con el mandato de Agustín de Iturbide', '0', 1), (17, 6, 'En 1821 en el mandato de José Magdaleno Ocampo', '0', 1), (18, 6, 'En 1916 en la epoca del Gral Veustiano Carranza', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (19, 7,  'Paz Universal', '0', 1), (20, 7, 'Venganza a nuestros pueblos', '0', 1), (21, 7, 'Siempre venceremos', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (22, 8,  'Evoca a la paz universal', '0', 1), (23, 8, 'Evocan a una venganza a nuestros pueblos', '0', 1), (24, 8, 'Evocan nuestros origenes', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (25, 9,  'Chihuahua', '0', 1), (26, 9, 'Labrador Retriever', '0', 1), (27, 9, 'Bulldog', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (28, 10, 'Un Lugar de comida rapida.', '0', 1), (29, 10, 'Restaurantes', '0', 1), (30, 10, 'Lugar de Comida', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (31, 11, 'Estaciones.', '0', 1), (32, 11, 'Paradas', '0', 1), (33, 11, 'Puestos', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (34, 12, 'Una Panadería.', '0', 1), (35, 12, 'Restaurantes', '0', 1), (36, 12, 'Lugar de Comida', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (37, 13, 'Alguien grande.', '0', 1), (38, 13, 'Una persona', '0', 1), (39, 13, 'Un animal', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (40, 14, 'Al Comprador.', '0', 1), (41, 14, 'Al Vendedor', '0', 1), (42, 14, 'Alguien que camina.', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (43, 15, 'Ciudad de México.', '0', 1), (44, 15, 'Al País.', '0', 1), (45, 15, 'Una región.', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (46, 16, 'Dia de la Bandera (25 de febrero).', '0', 1), (47, 16, 'Batalla de Puebla (8 de mayo)', '0', 1), (48, 16, 'Día del mal del puerco.', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (49, 17, 'Una Paloma.', '0', 1), (50, 17, 'Una Comida', '0', 1), (51, 17, 'Un Aguila', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (52, 18, 'Alguien grande.', '0', 1), (53, 18, 'Una persona', '0', 1), (54, 18, 'Un animal', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (55, 19, 'Sistema Río Magdalena.', '0', 1), (56, 19, 'Sistema Tequisquiac ', '0', 1), (57, 19, 'Sistema Río Pánuco .', '0', 1) ");


        // tabla de complemento -TANDA CAT. COMIDA - NIVEL MEDIO  -


        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (58, 20, '1500 Museos', '0', 1), (59, 20, '100 Museos', '0', 1), (60, 20, '560 Museos', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (61, 21, '1500 Museos', '0', 1), (62, 21, '200 Museos', '0', 1), (63, 21, '250 Museos ', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (64, 22, 'La Constitución de Apatzingán de 1814', '0', 1), (65, 22, 'Constitución de Régimen Centralista de 1824', '0', 1), (66, 22, 'Constitución de 1857', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (67, 23, 'Día de gracias', '0', 1), (68, 23, 'Semana Santa', '0', 1), (69, 23, 'Revolución', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (70, 24, 'Para dar la bienvenida.', '0', 1), (71, 24, 'Para el nacimiento.', '0', 1), (72, 24, 'Para celebrar.', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (73, 25,  'Tradicional Cumpleaños Feliz.', '0', 1), (74, 25, 'Cumpleaños Feliz.', '0', 1), (75, 25, 'A los bebes.', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (76, 26,  'Altamira ', '0', 1), (77, 26, 'Coatzacoalcos', '0', 1), (78, 26, 'Dos Bocas', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (79, 27,  'Vive el Visepresidente.', '0', 1), (80, 27, 'El presidente del Congreso.', '0', 1), (81, 27, 'Vive el Presidente del Senado.', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (82, 28,  'Letras', '0', 1), (83, 28, 'Artes', '0', 1), (84, 28, 'Musica', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (85, 29,  'Mario Molina', '0', 1), (86, 29, 'Octavio Paz', '0', 1), (87, 29, 'Alfonso García Robles', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (88, 30, 'Mario Molina.', '0', 1), (89, 30, 'Octavio Paz', '0', 1), (90, 30, 'Alfonso García Robles', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (91, 31, 'Mario Molina.', '0', 1), (92, 31, 'Octavio Paz', '0', 1), (93, 31, 'Alfonso García Robles', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (94, 32, '10', '0', 1), (95, 32, '20', '0', 1), (96, 32, '30', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (97, 33, '10', '0', 1), (98, 33, '20', '0', 1), (99, 33, '30', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (100, 34, 'Baile', '0', 1), (101, 34, 'La Danza', '0', 1), (102, 34, 'Musica.', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (103, 35, 'Los Pinos', '0', 1), (104, 35, 'Angel de la Independencia', '0', 1), (105, 35, 'Monumento de la Revolución.', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (106, 36, 'Revolución', '0', 1), (107, 36, 'Independencia.', '0', 1), (108, 36, 'El grito', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (109, 37, 'Banda.', '0', 1), (110, 37, 'Corridos', '0', 1), (111, 37, 'Regueton', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (112, 38, 'Sistema Río Magdalena.', '0', 1), (113, 38, 'Sistema Tequisquiac ', '0', 1), (114, 38, 'Sistema Río Pánuco ', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (115, 39, 'Tajín.', '0', 1), (116, 39, 'Teotihuacan', '0', 1), (117, 39, 'Cuetzalan', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (118, 40, 'Reserva de la Biosfera de la Mariposa Monarca.', '0', 1), (119, 40, 'Reserva de la Biosfera El Pinacate y Gran Desierto de Altar.', '0', 1), (120, 40, 'Reserva de la Biosfera Sian Ka an', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (121, 41, 'bosques tropicales, manglares y pantanos, así como una gran sección marina. Es el hábitat de más de 300 especies de pájaros y un gran número de vertebrados terrestres.', '0', 1), (122, 41, 'Sitio de migración e hibernación de las mariposas Monarca, único en el mundo ya que de encontrarse dispersas en un territorio de 5 millones de km2 ', '0', 1), (123, 41, 'Es uno de los sitos desérticos con mayor riqueza florística, por lo que se vuelve una zona para la conservación de plantas vasculares ', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (124, 42, 'La Plaza de la Revolución.', '0', 1), (125, 42, 'La Plaza Templo Mayor', '0', 1), (126, 42, ' La plaza principal ', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (127, 43, 'La Plaza de la Revolución ', '0', 1), (128, 43, 'Coyoacan', '0', 1), (129, 43, 'Angel de la Independencia', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (130, 44, '12 Mayo.', '0', 1), (131, 44, '15 Junio', '0', 1), (132, 44, '14 Julio', '0', 1) ");

        // Tabla de Preguntas -TANDA CAT. COMIDA - NIVEL AVANZADO -

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (133, 45, '12 Mayo.', '0', 1), (134, 45, '15 Junio', '0', 1), (135, 45, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (136, 46, '12 Mayo.', '0', 1), (137, 46, '15 Junio', '0', 1), (138, 46, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (139, 47, '12 Mayo.', '0', 1), (140, 47, '15 Junio', '0', 1), (141, 47, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (142, 48, '12 Mayo.', '0', 1), (143, 48, '15 Junio', '0', 1), (144, 48, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (145, 49, '12 Mayo.', '0', 1), (146, 49, '15 Junio', '0', 1), (147, 49, '14 Julio', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (148, 50, '12 Mayo.', '0', 1), (149, 50, '15 Junio', '0', 1), (150, 50, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (151, 51, '12 Mayo.', '0', 1), (152, 51, '15 Junio', '0', 1), (153, 51, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (154, 52, '12 Mayo.', '0', 1), (155, 52, '15 Junio', '0', 1), (156, 52, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (157, 53, '12 Mayo.', '0', 1), (158, 53, '15 Junio', '0', 1), (159, 53, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (160, 54, '12 Mayo.', '0', 1), (161, 54, '15 Junio', '0', 1), (162, 54, '14 Julio', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (163, 55, '12 Mayo.', '0', 1), (164, 55, '15 Junio', '0', 1), (165, 55, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (166, 56, '12 Mayo.', '0', 1), (167, 56, '15 Junio', '0', 1), (168, 56, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (169, 57, '12 Mayo.', '0', 1), (170, 57, '15 Junio', '0', 1), (171, 57, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (172, 58, '12 Mayo.', '0', 1), (173, 58, '15 Junio', '0', 1), (174, 58, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (175, 59, '12 Mayo.', '0', 1), (176, 59, '15 Junio', '0', 1), (177, 59, '14 Julio', '0', 1) ");


        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (178, 60, '12 Mayo.', '0', 1), (179, 60, '15 Junio', '0', 1), (180, 60, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (181, 61, '12 Mayo.', '0', 1), (182, 61, '15 Junio', '0', 1), (183, 61, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (184, 62, '12 Mayo.', '0', 1), (185, 62, '15 Junio', '0', 1), (186, 62, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (187, 63, '12 Mayo.', '0', 1), (188, 63, '15 Junio', '0', 1), (189, 63, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (190, 64, '12 Mayo.', '0', 1), (191, 64, '15 Junio', '0', 1), (192, 64, '14 Julio', '0', 1) ");

        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (193, 65, '12 Mayo.', '0', 1), (194, 65, '15 Junio', '0', 1), (195, 65, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (196, 66, '12 Mayo.', '0', 1), (197, 66, '15 Junio', '0', 1), (198, 66, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (199, 67, '12 Mayo.', '0', 1), (200, 67, '15 Junio', '0', 1), (201, 67, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (202, 68, '12 Mayo.', '0', 1), (203, 68, '15 Junio', '0', 1), (204, 68, '14 Julio', '0', 1) ");
        BasesDeDatos.execSQL("INSERT INTO t_complemento (id, co_pregunta, complemento, imagen, activo) VALUES (205, 69, '12 Mayo.', '0', 1), (206, 69, '15 Junio', '0', 1), (207, 69, '14 Julio', '0', 1) ");




    }


    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
